package com.cvi.controller;

import com.cvi.ApiDocument;
import com.cvi.auth.JwtTokenProvider;
import com.cvi.dto.CommentResponse;
import com.cvi.dto.PostRequest;
import com.cvi.dto.PostResponse;
import com.cvi.dto.UserResponse;
import com.cvi.post.domain.model.Post;
import com.cvi.post.domain.model.VaccinationType;
import com.cvi.service.UserService;
import com.cvi.user.domain.model.AgeRange;
import com.cvi.user.domain.model.SocialProvider;
import com.cvi.user.domain.model.User;
import com.cvi.user.domain.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.springframework.boot.test.mock.mockito.MockBean;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.BDDMockito.given;

@DisplayName("게시글, 좋아요, 댓글 컨트롤러 Mock 테스트 - 환경설정")
public abstract class PreprocessPostControllerTest extends ApiDocument {

    protected static final Long USER_ID = 1L;
    protected static final Long POST_ID = 1L;
    protected static final Long COMMENT_ID = 1L;
    protected static final Long LIKE_ID = 1L;
    protected static final String BEARER = "Bearer ";
    protected static final String ACCESS_TOKEN = "{ACCESS TOKEN generated by JWT}";

    @MockBean
    protected UserService userService;

    @MockBean
    private UserRepository userRepository;

    @MockBean
    protected JwtTokenProvider jwtTokenProvider;

    protected User user;
    protected User anotherUser;
    protected UserResponse userResponse;

    protected PostRequest request;
    protected PostResponse postResponse;

    protected List<CommentResponse> commentResponses;

    @BeforeEach
    void setUp() {
        user = User.builder()
                .id(USER_ID)
                .nickname("user")
                .ageRange(AgeRange.TEENS)
                .profileUrl("naver.com/profile")
                .socialId("{Unique ID received from social provider}")
                .socialProvider(SocialProvider.NAVER)
                .build();
        anotherUser = User.builder()
                .id(USER_ID + 1)
                .nickname("another_user")
                .ageRange(AgeRange.TWENTIES)
                .profileUrl("kakao.com/profile")
                .socialId("{Unique ID received from social provider}")
                .socialProvider(SocialProvider.KAKAO)
                .build();
        Post post = Post.builder()
                .id(POST_ID)
                .user(user)
                .vaccinationType(VaccinationType.ASTRAZENECA)
                .content("Post Content")
                .createdAt(LocalDateTime.now())
                .viewCount(0)
                .build();

        request = new PostRequest("글 내용", VaccinationType.PFIZER);

        userResponse = UserResponse.of(user, null);
        postResponse = PostResponse.of(post, user);

        given(jwtTokenProvider.isValidToken(ACCESS_TOKEN)).willReturn(true);
        given(jwtTokenProvider.getPayload(ACCESS_TOKEN)).willReturn(String.valueOf(user.getId()));
        given(userService.findUserById(any(Long.class))).willReturn(user);
        given(userRepository.findById(anyLong())).willReturn(Optional.of(user));
    }
}
