/*
package com.backjoongwon.cvi;

public class DummyData {
    public static final String DUMMY_DATA_10000 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean odio orci, venenatis sed vulputate quis, ultricies non massa. Nulla commodo justo at metus consequat hendrerit. Sed nec mauris urna. Nunc turpis est, pulvinar vitae tellus non, sollicitudin commodo ligula. Nullam est ante, faucibus id leo malesuada, elementum hendrerit tortor. Sed id metus eu leo aliquet faucibus et ac felis. Aliquam nec laoreet est, interdum tempor mauris. Etiam feugiat, ante sed ullamcorper euismod, ligula lorem ultricies nisi, nec bibendum est dui eget metus. Nam ac congue libero.\n" +
            "\n" +
            "Pellentesque blandit risus quis consequat maximus. Donec ullamcorper facilisis ante, non luctus ex condimentum quis. Quisque pulvinar sagittis nulla at pulvinar. Nam mi urna, rutrum non erat id, dapibus ultricies tortor. Aliquam malesuada metus eu erat imperdiet pulvinar. In eget iaculis metus. Suspendisse nec orci auctor, egestas elit ut, ultrices sapien. Suspendisse tincidunt iaculis tellus id scelerisque. In non congue orci. Aliquam erat volutpat. Sed iaculis diam at justo porttitor, pulvinar tristique mauris finibus. Sed lobortis venenatis nunc sit amet cursus. Aenean mattis enim lectus, sit amet ullamcorper arcu sodales id.\n" +
            "\n" +
            "Quisque ornare tincidunt enim. Maecenas quis laoreet mi, in hendrerit lacus. Praesent id turpis in sapien euismod accumsan. Cras euismod sollicitudin sem nec aliquet. Aenean magna ex, luctus ut nulla id, consectetur sodales risus. Curabitur interdum elit et consectetur aliquet. Morbi non fringilla nisl.\n" +
            "\n" +
            "Donec neque elit, dapibus in malesuada at, convallis in dui. Donec consectetur dignissim magna, et ultrices felis finibus id. Etiam a urna lectus. Proin neque metus, iaculis eget mauris ac, congue vulputate nisl. Pellentesque sodales felis eu diam scelerisque molestie. Pellentesque commodo tempus vestibulum. Proin non quam egestas, pulvinar augue eu, hendrerit lorem. Aenean vel mollis nisi, sit amet scelerisque dolor. Vestibulum feugiat eleifend tellus, ac auctor ex ultricies ut. Aenean volutpat vulputate risus a euismod. Nulla tincidunt massa pulvinar dapibus pharetra. Curabitur a blandit lectus, vel posuere purus. Ut erat diam, bibendum vitae luctus quis, sollicitudin eget magna. Phasellus dignissim in odio feugiat blandit. Etiam porta sollicitudin massa sit amet auctor. Suspendisse rutrum pellentesque fermentum.\n" +
            "\n" +
            "Maecenas non faucibus lorem, eget tempor sapien. Pellentesque ac augue id justo malesuada blandit. In auctor varius scelerisque. Nunc cursus id elit et facilisis. Aenean in egestas erat. Nullam eleifend vitae diam at vehicula. Suspendisse ut diam at elit mollis accumsan. Nulla facilisi.\n" +
            "\n" +
            "Etiam vel elit a lorem efficitur ullamcorper id laoreet neque. Pellentesque nec imperdiet urna. Vestibulum sodales ante ac justo rutrum, id tempus nulla tincidunt. Aenean accumsan posuere enim eu vestibulum. Donec ex metus, molestie ac enim a, ultrices dapibus ipsum. Pellentesque neque quam, lobortis a lacus sed, molestie finibus urna. Curabitur a dolor quis ante malesuada blandit.\n" +
            "\n" +
            "Aliquam in massa ac odio mollis malesuada vel et diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam placerat feugiat elit eget iaculis. Cras arcu arcu, suscipit ac mi eu, pharetra pulvinar diam. Praesent tincidunt, lorem id auctor mollis, mi ipsum rhoncus mauris, vel placerat elit massa quis leo. Curabitur et mi fringilla quam blandit pulvinar. Nunc enim sem, maximus vitae sem at, posuere euismod risus. Duis euismod ullamcorper sem eget semper. Curabitur et neque vitae neque euismod pharetra. Curabitur vel mi accumsan, facilisis neque nec, consequat lectus. Mauris tristique velit vitae congue consequat. Donec sit amet tortor sed ante congue bibendum a cursus libero.\n" +
            "\n" +
            "Praesent tristique eget neque quis bibendum. Donec quis ante sed orci varius maximus. Praesent gravida in massa nec tincidunt. Nulla facilisi. Praesent magna enim, placerat eu libero id, hendrerit malesuada diam. Fusce vestibulum nulla ut erat elementum iaculis. Fusce eu posuere purus. Quisque efficitur rutrum metus quis vestibulum.\n" +
            "\n" +
            "Fusce vitae semper orci. Quisque eu urna lobortis, auctor magna quis, pellentesque sem. Etiam vitae vehicula dolor, sit amet pretium nulla. Ut efficitur pretium augue in luctus. Vestibulum in odio a diam tristique efficitur. Nulla egestas quis risus at imperdiet. Maecenas eget bibendum nisi, eu faucibus odio.\n" +
            "\n" +
            "Vestibulum porttitor a nulla a varius. Pellentesque nec lacinia nunc, nec elementum est. Vivamus commodo tortor et velit euismod blandit. Maecenas luctus pharetra velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque vulputate leo at nisi rutrum mattis. Pellentesque luctus malesuada turpis. Duis non erat quis eros hendrerit accumsan.\n" +
            "\n" +
            "Vivamus placerat, mi vitae fermentum pulvinar, massa lacus commodo tellus, in elementum neque purus elementum odio. Donec auctor volutpat finibus. Cras feugiat eu ipsum eu tincidunt. Sed non tortor ultrices, cursus sapien in, euismod nibh. Nunc interdum viverra dignissim. Nunc finibus finibus fermentum. Proin faucibus blandit lorem, nec pretium quam fermentum nec. In id euismod nisi, eu euismod tellus. Nulla interdum, arcu id vehicula viverra, lacus velit pellentesque sapien, sit amet sollicitudin erat metus in augue. Proin in congue dui. Aenean pharetra odio nec ornare suscipit. Nunc et libero magna. In ut quam ante.\n" +
            "\n" +
            "Fusce dignissim scelerisque neque ut tincidunt. Quisque ut lacinia metus, ut luctus lacus. Vivamus et dictum metus, et cursus libero. Phasellus turpis libero, hendrerit a mollis ac, semper feugiat urna. Nullam id sagittis quam, eu facilisis enim. Maecenas in tortor lacinia, aliquet felis non, congue leo. Proin enim massa, malesuada interdum tempus eget, venenatis id tellus. Etiam ultricies, lacus quis egestas pulvinar, ipsum nibh luctus nisl, sed interdum felis leo eu leo. Mauris faucibus semper nisi at rhoncus. Quisque vel venenatis nisi. Ut consectetur mauris nec magna lacinia fringilla. Nullam luctus fermentum odio. Donec ultricies augue sed dui elementum, sed euismod nibh laoreet. Maecenas condimentum sapien at faucibus mattis. Pellentesque porttitor sed tortor et faucibus. Aliquam sed quam eget lacus aliquam molestie sit amet at urna.\n" +
            "\n" +
            "Curabitur eget metus interdum diam volutpat efficitur. Maecenas viverra massa in est volutpat, eu convallis nisi eleifend. Sed molestie sagittis mauris. Quisque id arcu vitae lorem tristique pretium. Mauris cursus ex dolor, nec malesuada urna iaculis sit amet. Mauris pharetra magna eget sapien varius aliquet. Maecenas pulvinar orci non condimentum dictum. Maecenas faucibus rutrum arcu, nec aliquet elit dignissim ut. Integer ullamcorper massa eu lectus malesuada rutrum. Vestibulum maximus euismod ante, a euismod augue dapibus non. Praesent tellus orci, tempus quis dignissim id, ultricies porta felis. Maecenas ut ipsum dolor.\n" +
            "\n" +
            "Mauris pulvinar nisi et lorem elementum tristique. Vestibulum tempus, nunc id dictum condimentum, felis nisl dapibus sem, sit amet commodo metus tortor ut dui. Suspendisse viverra urna efficitur massa pellentesque mattis. Sed posuere, urna mollis bibendum ornare, felis dui congue nibh, sed placerat velit tellus vitae tellus. Cras maximus blandit diam nec feugiat. Nunc bibendum erat vitae libero lobortis pulvinar. In ut aliquam orci. Donec feugiat, ex congue pretium dictum, justo enim feugiat risus, malesuada ornare purus diam quis turpis. Phasellus vitae est id turpis consectetur semper. Quisque vel euismod justo, molestie vestibulum leo. Donec nibh nunc, rutrum ut diam ut, tincidunt bibendum est. Donec tristique dolor et interdum mollis. Aliquam a mi nulla.\n" +
            "\n" +
            "Morbi hendrerit sagittis nulla quis porta. Phasellus vitae vehicula sem, non mollis lorem. Donec mollis vestibulum nunc, vitae laoreet neque consectetur eget. Sed varius urna et urna porttitor, eu imperdiet velit sollicitudin. Nulla dolor dui, imperdiet at facilisis eget, scelerisque sed nisi. Integer maximus congue viverra. Ut mattis faucibus fermentum. Donec malesuada mattis sollicitudin. Maecenas vel est fringilla, elementum lectus et, rutrum mauris. Sed non viverra purus, ut finibus felis. Nunc ac fermentum tortor, non faucibus mauris.\n" +
            "\n" +
            "Aliquam erat volutpat. Etiam nulla erat, pretium id enim quis, hendrerit congue ligula. Sed vitae accumsan sem. Praesent ligula turpis, bibendum vitae nulla ut, efficitur commodo erat. Vestibulum odio nibh, convallis id ligula eget, pretium condimentum erat. Nam molestie tortor nec nibh ornare, at ultricies massa molestie. Aenean sodales dolor risus, sed fringilla purus interdum accumsan. In hac habitasse platea dictumst. In sit amet nisl nec leo sagittis tincidunt. Pellentesque at ligula at sapien suscipit facilisis. Sed nec feugiat neque. Sed eu neque lectus. Nullam sed magna ac mi pretium tristique. Integer at velit erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris efficitur nisl eget metus porta, ut tincidunt felis ultricies.\n" +
            "\n" +
            "Nullam sit amet maximus lacus. Suspendisse elit erat, vestibulum vel magna mollis, iaculis hendrerit eros. Praesent quis eros sed lorem faucibus feugiat vitae non sapien. Aliquam non mi sed dolor accumsan finibus id in odio. Nunc a placerat mauris. In hac habitasse platea dictumst. Curabitur quis diam facilisis, vulputate ligula nec, auctor mauris. Suspendisse potenti. Duis tempor neque diam, vel ornare metus fringilla quis. Proin a odio non nisi egestas blandit. Vestibulum sit amet leo odio. Nulla quis quam vel mauris eleifend dapibus et sed sapien. Suspendisse cursus porta augue, sed scelerisque libero faucibus quis. Vestibulum ipsum sem, pulvinar id tellus a, tincidunt cursus velit. Pellentesque tristique interdum est, nec sollicitudin justo efficitur quis.\n" +
            "\n" +
            "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed tellus nulla, fringilla ut tortor ut, pellentesque faucibus dui. Donec posuere risus ut enim fermentum tristique. Nullam a erat nec massa rutrum bibendum. Duis rutrum porttitor massa nunc.";
}
*/
