const LINE_LIMIT = {
  PREVIEW_ITEM: 3,
  REVIEW_ITEM: 3,
  MY_COMMENT_ITEM: 1,
};

const COMMENT_LIMIT = {
  MIN_LENGTH: 1,
  MAX_LENGTH: 300,
};

const NICKNAME_LIMIT = {
  MIN_LENGTH: 1,
  MAX_LENGTH: 20,
};

const PAGING_SIZE = 10;

export { LINE_LIMIT, COMMENT_LIMIT, NICKNAME_LIMIT, PAGING_SIZE };
