import PALETTE from './palette';

const VACCINE_COLOR = {
  ASTRA_ZENECA: PALETTE.GRAY100,
  MODERNA: PALETTE.RED500,
  PFIZER: PALETTE.PURPLE300,
  JANSSEN: PALETTE.BLUE500,
};

export { VACCINE_COLOR };
