import PALETTE from './palette';

const VACCINE_COLOR = {
  ASTRA_ZENECA: PALETTE.GRAY100,
  MODERNA: PALETTE.RED500,
  PFIZER: PALETTE.PURPLE300,
  JANSSEN: PALETTE.BLUE500,
};

const FONT_COLOR = {
  BLACK: PALETTE.GRAY900,
  WHITE: PALETTE.WHITE,
  PURPLE_GRAY: PALETTE.NAVY300,
  GRAY: PALETTE.GRAY700,
  LIGHT_GRAY: PALETTE.GRAY300,
  GREEN: PALETTE.GREEN500,
};

const THEME_COLOR = {
  WHITE: PALETTE.WHITE,
};

export { VACCINE_COLOR, FONT_COLOR, THEME_COLOR };
